\documentclass[12pt]{article}

<<include=FALSE>>=

library(knitr)
library(tikzDevice)
opts_chunk$set(
echo=FALSE, results='asis',cache=FALSE,warning=FALSE,error=FALSE,dev='tikz',message=FALSE,autodep = TRUE
    )

options(tikzDefaultEngine = "pdftex")

@

<<lsoAnalysis>>=
source('src/winSelect.r')
#source('src/lso.r')
@
<<timeSeriesAnalysis>>=
source('src/timeSeries2.r')
@

\begin{document}

\begin{figure}
<<test,fig.height=3,fig.width=3,dev='tikz'>>=
plot(1:10)
@


\end{figure}

\end{document}